linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell

run:
  deadline: 5m

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec

output:
  format: colored-line-number
